### ISSUE TITLE
 Help me please

### ISSUE THREAD

**Issue by Snesik** [Tygon/SteamGuard#2]
Good afternoon, can you tell me how to run your code? I'm a beginner in development, and unfortunately, it doesn't work out ... =)
But I really want to understand your code.

**Comment by James-LG** [comment]
Hi, I never got this project to a state I was really happy with and mostly abandoned it. I highly recommend this C# project instead: https://github.com/geel9/SteamAuth

If you have any specific questions though I'm happy to answer.

**Comment by Snesik** [comment]
Thank you for your answer, I only managed to use the code generator, for which I thank you very much. I'm just starting to figure out the rest. Do you mind if I use your code, indicating you?
Sorry for the bad English use google

**Comment by James-LG** [comment]
Yep, use it for whatever you like, that's why I posted it here :)
